apps/about/urls.py
from django.urls import path
from apps.about.views import AboutView


app_name = 'about'


urlpatterns = [
    path('', AboutView.as_view(), name='about'),
]

apps/blog/urls.py
from django.urls import path
from apps.blog.views import (
    HomeView, PostDetailView, post_share, post_search
)
from apps.blog.feeds import LatestPostsFeed


app_name = 'blog'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<int:year>/<int:month>/<int:day>/<str:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('search/', post_search, name='post_search'),
    path('detail/<str:slug>/share/', post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

apps/contact/urls.py
from django.urls import path
from apps.contact.views import ContactView

app_name = 'contact'


urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
]

core/urls.py
import os
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

from apps.blog.sitemaps import PostSitemap
from ckeditor_uploader.views import upload, browse

sitemaps = {
    'posts': PostSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('apps.about.urls', namespace='about')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('', include('apps.category.urls', namespace='category')),
    path('', include('apps.blog.urls', namespace='blog')),

    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(browse)), name='ckeditor_browse'),

    # sitemaps
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/feature/models/extend_blog.py
from django.db import models

from base.models import BaseModel
from apps.feature.utils import extend_image_directory_path


class ExtendBlog(models.Model):
    title = models.CharField(
        max_length=255
    )
    image = models.ImageField(
        upload_to=extend_image_directory_path
    )
    link = models.URLField(
        max_length=500,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=6,
        choices=BaseModel.StatusChoices.choices,
        default=BaseModel.StatusChoices.PUBLISHED
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('created_at',)
        verbose_name = "Extend Blog"
        verbose_name_plural = "Extend Blog"
        db_table = "db_extend_blog"

apps/feature/models/social_media.py
from django.db import models


class SocialMedia(models.Model):
    facebook = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    twitter = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    instagram = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    linkedin = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    pintest = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    youtube = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    stack_overflow = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    dev_to = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    figma = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    medium = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    github = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    gitlab = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )
    bitbucket = models.URLField(
        max_length=300,
        null=True,
        blank=True
    )

    def __str__(self) -> str:
        return "Social Media"

    class Meta:
        verbose_name = "Social Media"
        verbose_name_plural = "Social Media"
        db_table = "db_social_media"

base/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _

User = settings.AUTH_USER_MODEL


class BaseModel(models.Model):
    class StatusChoices(models.TextChoices):
        PUBLISHED = 'PUB', _('Published')
        UNPUBLISHED = 'UNPUB', _('Unpublished')
        DRAFT = 'DR', _('Draft')
        ARCHIVED = 'ARC', _('Archived')

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True
        app_label = 'base'

apps/feature/views.py
from django.shortcuts import render

# Create your views here.

core/templates/base/categories.html
{% load static %}


<aside class="widget widget_categories text-center">
    <h3 class="widget-title">Categories</h3>
    <ul>
        {% for context in category_context %}
        <li><a href="#" title="Nature">{{ context.name }}</a></li>
        {% endfor %}
    </ul>
</aside>

core/templates/base/css.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'assets/revolution/css/settings.css' %}">
<!-- Library -->
<link href="{% static 'assets/css/lib.css' %}" rel="stylesheet">

<!-- Custom - Common CSS -->
<link rel="stylesheet" href="{% static 'assets/css/rtl.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">

<!--[if lt IE 9]>
<script src="{% static 'js/html5/respond.min.js' %}"></script>
<![endif]-->

<!-- UPPER JS  -->

<!-- JQuery v1.12.4 -->
<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>

core/templates/base/feature.html
{% load static %}


<aside class="widget widget_tranding_post">
    <h3 class="widget-title">FEATURE Posts</h3>
    <div id="trending-widget" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for context in feature_post %}
                {% if forloop.first %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item  ">
                {% endif %}
                <div class="trnd-post-box">
                    <div class="post-cover">
                        <a href="#"><img src="{{ context.cover.url }}" style="width: 350px; height: 200px;" alt="{{ context.title }}"/></a>
                    </div>
                    <span class="post-category">
                        <a href="#" title="Lifestyle">{{ context.category }}</a>
                    </span>
                    <h3 class="post-title"><a href="#">{{ context.title }}</a></h3>
                </div>
            </div>
            {% endfor %}
        </div>
        <ol class="carousel-indicators">
            {% for context in feature_post %}
                {% if forloop.first %}
                    <li data-target="#trending-widget" data-slide-to="{{forloop.counter0}}" class="active"></li>
                {% else %}
                    <li data-target="#trending-widget" data-slide-to="{{forloop.counter0}}"></li>
                {% endif %}
            {% endfor %}
        </ol>
    </div>
</aside>

core/templates/base/footer.html
{% load static %}


<div class="container">
    <ul class="ftr-social">
        <li><a href="{{ socialmedia.facebook }}" target="_blank" title="Facebook"><i class="fa fa-facebook"></i>Facebook</a></li>
        <li><a href="{{ socialmedia.twitter }}" target="_blank" title="Twitter"><i class="fa fa-twitter"></i>twitter</a></li>
        <li><a href="{{ socialmedia.instagram }}" target="_blank" title="Instagram"><i class="fa fa-instagram"></i>Instagram</a></li>
        <li><a href="{{ socialmedia.linkedin }}" target="_blank" title="Pinterest"><i class="fa fa-linkedin-square"></i>LinkedIn</a></li>
        <li><a href="{{ socialmedia.youtube }}" target="_blank" title="Youtube"><i class="fa fa-youtube"></i>youtube</a></li>
        <li><a href="{{ socialmedia.github }}" target="_blank" title="Youtube"><i class="fa fa-github-square"></i>youtube</a></li>
    </ul>
    <div class="copyright">
        <p>Copyright @ 2017 MINIMAG</p>
    </div>
</div><!-- Container /- -->

core/templates/base/gallery.html
{% load static %}


<div class="container-fluid no-left-padding no-right-padding instagram-block">
    <ul class="instagram-carousel">
        {% for context in extend_blog_context %}
        <li>
            <a href="{{ context.link }}" target="_blank"><img src="{{ context.image.url }}" style="width: 319px; height: 319px;" alt="Instagram"/></a>
        </li>
        {% endfor %}
    </ul>
</div>

core/templates/base/header.html
{% load static %}

<header class="container-fluid no-left-padding no-right-padding header_s header-fix header_s1">

    <!-- SidePanel -->
    <div id="slidepanel-1" class="slidepanel">
        <!-- Top Header -->
        <div class="container-fluid no-right-padding no-left-padding top-header">
            <!-- Container -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-6">
                        <ul class="top-social">
                            <li><a href="{{ socialmedia.facebook }}" target="_blank" title="Facebook"><i class="ion-social-facebook-outline"></i></a></li>
                            <li><a href="{{ socialmedia.twitter }}" target="_blank" title="Twitter"><i class="ion-social-twitter-outline"></i></a></li>
                            <li><a href="{{ socialmedia.instagram }}" target="_blank" title="Instagram"><i class="ion-social-instagram-outline"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 logo-block">
                        <a href="{% url 'blog:home' %}" title="Logo">jTro Log</a>
                    </div>
                    <div class="col-lg-4 col-6">
                        <ul class="top-right user-info">
                            <li>
                                <a href="#search-box" data-toggle="collapse" class="search collapsed" title="Search">
                                    <i class="pe-7s-search sr-ic-open"></i><i class="pe-7s-close sr-ic-close"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div><!-- Container /- -->
        </div><!-- Top Header /- -->
    </div><!-- SidePanel /- -->

    <!-- Menu Block -->
    <div class="container-fluid no-left-padding no-right-padding menu-block">
        <!-- Container -->
        <div class="container">
            <nav class="navbar ownavigation navbar-expand-lg">
                <a class="navbar-brand" href="{% url 'blog:home' %}">minimag</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navbar1" aria-controls="navbar1" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbar1">
                    <ul class="navbar-nav">
                        <li><a class="nav-link" title="Contact" href="{% url 'blog:home' %}">Home</a></li>
                        <li><a class="nav-link" title="Contact" href="{% url 'about:about' %}">About</a></li>
                        <li><a class="nav-link" title="Contact" href="{% url 'contact:contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div id="loginpanel-1" class="desktop-hide">
                    <div class="right toggle" id="toggle-1">
                        <a id="slideit-1" class="slideit" href="#slidepanel"><i class="fo-icons fa fa-inbox"></i></a>
                        <a id="closeit-1" class="closeit" href="#slidepanel"><i class="fo-icons fa fa-close"></i></a>
                    </div>
                </div>
            </nav>
        </div><!-- Container /- -->
    </div><!-- Menu Block /- -->
    <!-- Search Box -->
    <div class="search-box collapse" id="search-box">
        <div class="container">
            <form method="get" action="{% url 'blog:post_search' %}">
                <div class="input-group">
                    <input type="text" name="query" class="form-control" placeholder="Search..." required>
                    <span class="input-group-btn">
						<button class="btn btn-secondary" type="submit"><i class="pe-7s-search"></i></button>
					</span>
                </div>
            </form>
        </div>
    </div><!-- Search Box /- -->
</header>

core/templates/base/js.html
{% load static %}

<!-- Library - Js -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/lib.js' %}"></script>

<!-- REVOLUTION JS FILES -->
<script type="text/javascript" src="{% static 'assets/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>

<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'assets/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>

<!-- Library - Theme JS -->
<script src="{% static 'assets/js/functions.js' %}"></script>

core/templates/base/latest.html
{% load static %}
{% load blog_tags %}


<aside class="widget widget_latestposts">
    <h3 class="widget-title">Latest Posts</h3>
    {% for context in latest_posts %}
    <div class="latest-content">
        <a href="{{ context.get_absolute_url }}" title="Recent Posts">
            <i><img src="{{ context.cover.url }}" style="width: 100px; height: 80px" class="wp-post-image" alt="{{ context.title }}"/></i>
        </a>
        <h5>
            <a title="Beautiful Landscape View of Rio de Janeiro" href="#">{{ context.title }}</a>
        </h5>
        <span><a href="#">{{ context.publish|date }}</a></span>
    </div>
    {% endfor %}
</aside>

core/templates/base/popular.html
{% load static %}


<aside class="widget widget_latestposts">
                            <h3 class="widget-title">Popular Posts</h3>
                            <div class="latest-content">
                                <a href="#" title="Recent Posts"><i><img src="https://via.placeholder.com/100x80"
                                                                         class="wp-post-image" alt="blog-1"/></i></a>
                                <h5><a title="Beautiful Landscape View of Rio de Janeiro" href="#">Beautiful Landscape
                                    View of Rio de Janeiro</a></h5>
                                <span><a href="#">march 14, 2017</a></span>
                            </div>
                            <div class="latest-content">
                                <a href="#" title="Recent Posts"><i><img src="https://via.placeholder.com/100x80"
                                                                         class="wp-post-image" alt="blog-1"/></i></a>
                                <h5><a title="Enjoy Your Holiday with Adventures" href="#">Enjoy Your Holiday with
                                    Adventures</a></h5>
                                <span><a href="#">march 15, 2017</a></span>
                            </div>
                            <div class="latest-content">
                                <a href="#" title="Recent Posts"><i><img src="https://via.placeholder.com/100x80"
                                                                         class="wp-post-image" alt="blog-1"/></i></a>
                                <h5><a title="Best Photography Experience Shooting" href="#">Best Photography Experience
                                    Shooting</a></h5>
                                <span><a href="#">march 15, 2017</a></span>
                            </div>
                            <div class="latest-content">
                                <a href="#" title="Recent Posts"><i><img src="https://via.placeholder.com/100x80"
                                                                         class="wp-post-image" alt="blog-1"/></i></a>
                                <h5><a title="How to Forecast Your Retirement Savings" href="#">How to Forecast Your
                                    Retirement Savings</a></h5>
                                <span><a href="#">march 16, 2017</a></span>
                            </div>
                        </aside>

core/templates/base/slider.html
{% load static %}


<div class="container-fluid no-left-padding no-right-padding slider-section">
    <div id="mm-slider-1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="mm-slider-1"
         data-source="gallery">
        <!-- START REVOLUTION SLIDER 5.4.1 fullwidth mode -->
        <div id="mm-slider-1" class="rev_slider fullwidthabanner" data-version="5.4.1">
            <ul>
                <!-- SLIDE  -->
                {% for context in slider_context %}
                <li data-index="rs-28"
                    data-transition="random-static,random-premium,random,boxslide,slotslide-horizontal,slotslide-vertical,boxfade,slotfade-horizontal,slotfade-vertical"
                    data-slotamount="default,default,default,default,default,default,default,default,default,default"
                    data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on"
                    data-easein="default,default,default,default,default,default,default,default,default,default"
                    data-easeout="default,default,default,default,default,default,default,default,default,default"
                    data-masterspeed="default,default,default,default,default,default,default,default,default,default"
                    data-rotate="0,0,0,0,0,0,0,0,0,0" data-saveperformance="off" class="slide-overlay"
                    data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4=""
                    data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10=""
                    data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="{{ context.cover.url }}" alt="{{ context.title }}" title="slide-1" width="100%"
                         style="width: 100%;"
                         data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"
                         class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->

                    <!-- LAYER NR. 4 -->
                    <a class="slidecnt1 tp-caption tp-layer-selectable tp-resizeme category-link" href="{{ context.get_absolute_url }}"
                       target="_self" rel="nofollow" id="slide-28-layer-1"
                       data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                       data-y="['middle','middle','middle','middle']" data-voffset="['-56','-70','-70','-57']"
                       data-fontsize="['14','14','18','18']"
                       data-height="none"
                       data-whitespace="nowrap"
                       data-type="text"
                       data-actions=''
                       data-responsive_offset="on"
                       data-frames='[{"delay":0,"speed":1000,"frame":"0","from":"z:0;rX:0deg;rY:0;rZ:0;sX:2;sY:2;skX:0;skY:0;opacity:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);br:0px 0px 0px 0px;"}]'
                       data-textAlign="['inherit','inherit','inherit','inherit']"
                       data-paddingtop="[0,0,0,0]"
                       data-paddingright="[0,0,0,0]"
                       data-paddingbottom="[0,0,0,0]"
                       data-paddingleft="[0,0,0,0]">{{ context.category }} </a>

                    <!-- LAYER NR. 5 -->
                    <a class="slidecnt2 tp-caption tp-layer-selectable tp-resizeme post-title" href="{{ context.get_absolute_url }}"
                       target="_self" rel="nofollow"
                       id="slide-28-layer-2"
                       data-x="['center','center','center','center']" data-hoffset="['0','-1','-1','-1']"
                       data-y="['middle','middle','middle','middle']" data-voffset="['6','-5','-5','-5']"
                       data-fontsize="['40','30','30','23']"
                       data-lineheight="['40','40','40','30']"
                       data-width="['601','601','601','435']"
                       data-height="['81','81','81','none']"
                       data-whitespace="normal"
                       data-type="text"
                       data-actions=''
                       data-responsive_offset="on"
                       data-frames='[{"delay":0,"speed":1500,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                       data-textAlign="['center','center','center','center']"
                       data-paddingtop="[0,0,0,0]"
                       data-paddingright="[0,0,0,0]"
                       data-paddingbottom="[0,0,0,0]"
                       data-paddingleft="[0,0,0,0]">{{ context.title }} and Advanced</a>

                    <!-- LAYER NR. 6 -->
{#                    <a class="slidecnt3 tp-caption rev-btn tp-layer-selectable" href="{{ context.get_absolute_url }}" target="_self"#}
{#                       rel="nofollow" id="slide-28-layer-3"#}
{#                       data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"#}
{#                       data-y="['middle','middle','middle','middle']" data-voffset="['80','73','73','59']"#}
{#                       data-width="none"#}
{#                       data-height="none"#}
{#                       data-whitespace="nowrap"#}
{#                       data-type="button"#}
{#                       data-actions=''#}
{#                       data-responsive_offset="on"#}
{#                       data-responsive="off"#}
{#                       data-frames='[{"delay":0,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power2.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(21,21,21);bg:rgba(255,255,255,1);"}]'#}
{#                       data-textAlign="['inherit','inherit','inherit','inherit']"#}
{#                       data-paddingtop="[2,2,2,2]"#}
{#                       data-paddingright="[20,20,20,20]"#}
{#                       data-paddingbottom="[0,0,0,0]"#}
{#                       data-paddingleft="[20,20,20,20]">READ MORE </a>#}
                </li>
                {% endfor %}
            </ul>
            <div class="tp-bannertimer tp-bottom"></div>
        </div>
    </div><!-- END REVOLUTION SLIDER -->
</div>

core/templates/base/socialmedia.html
{% load static %}

<aside class="widget widget_social">
    <h3 class="widget-title">FOLLOW US</h3>
    <ul>
        <li><a href="{{ socialmedia.facebook }}" target="_blank" title=""><i class="ion-social-facebook-outline"></i></a></li>
        <li><a href="{{ socialmedia.twitter }}" target="_blank" title=""><i class="ion-social-twitter-outline"></i></a></li>
        <li><a href="{{ socialmedia.instagram }}" target="_blank" title=""><i class="ion-social-instagram-outline"></i></a></li>
        <li><a href="{{ socialmedia.pintest }}" target="_blank" title=""><i class="ion-social-pinterest-outline"></i></a></li>
        <li><a href="{{ socialmedia.linkedin }}" target="_blank" title=""><i class="ion-social-linkedin-outline"></i></a></li>
    </ul>
</aside>

core/templates/base/tags.html
{% load blog_tags %}
{% load static %}

<aside class="widget widget_tags_cloud">
    <h3 class="widget-title">Tags</h3>
    <div class="tagcloud">
{#        I've written {% total_posts %} posts so far.#}
{#        <hr/>#}
        {% for tag in tag_context %}
        <a href="#" title="Fashion">{{ tag.name }}</a>
        {% endfor %}
    </div>
</aside>

core/templates/base/trending.html
{% load static %}


<div class="container-fluid no-left-padding no-right-padding trending-section">
    <!-- Container -->
    <div class="container">
        <!-- Section Header -->
        <div class="section-header">
            <h3>Trending</h3>
        </div><!-- Section Header /- -->
        <div class="trending-carousel">
            {% for context in trending_post %}
            <div class="type-post">
                <div class="entry-cover"><a href="{{ context.get_absolute_url }}">
                    <img src="{{ context.cover.url }}" style="width: 400px; height: 170px;" alt="{{ context.title }}"/></a>
                </div>
                <div class="entry-content">
                    <div class="entry-header">
                        <span><a href="{{ context.get_absolute_url }}" title="Art">{{ context.category }}</a></span>
                        <h3 class="entry-title"><a href="#">{{ context.title }}</a></h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div><!-- Container /- -->
</div>

core/templates/base/videos.html
{% load static %}


<aside class="widget widget_instagram">
    <h3 class="widget-title">Gallery</h3>
    <ul>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
        <li><a href="#"><img src="https://via.placeholder.com/111x111" alt="Instagram"/></a></li>
    </ul>
</aside>